### ISSUE TITLE
stack size computation is broken

### ISSUE THREAD

**Issue by pwaller** [serprex/byteplay#3]
I haven't tested the py3 version, but on python 2, this breaks the stack size computation and results in a segmentation fault or an assertion failure if you happen to be running debug python.

The following code prints old stacksize = 2, new stacksize = 0, and then crashes.

```
def rebuild_function():
    import byteplay as B

    c = B.Code.from_code(func.func_code)
    code = c.to_code()

    args = code, func.func_globals, func.func_name, func.func_defaults, func.func_closure
    return types.FunctionType(*args)

def testfunc():
    return VALUE, ANOTHER

newfunc = rebuild_function(testfunc)

print "Orig stacksize: ", testfunc.func_code.co_stacksize
print "New stacksize: ", newfunc.func_code.co_stacksize

# crashes
newfunc()
```

**Comment by peterazmanov** [comment]
I've encountered the issue and tried to fix it [peterazmanov/byteplay](https://github.com/peterazmanov/byteplay). My changes stopped crashes, but the code requires further testing.

**Comment by pwaller** [comment]
@peterazmanov since you're dealing with this now, would you mind writing a new issue? It would probably be clearer than my issue as I wrote it here :)
